### ISSUE TITLE
怎么导出onnx格式？

### ISSUE THREAD

**Issue by lmk123568** [HankYe/PAGCP#2]
提供的pkl文件怎么加载到yolov5然后导出onnx？

**Comment by HankYe** [comment]
> 提供的pkl文件怎么加载到yolov5然后导出onnx？

您好，感谢您的关注和提问！我们已经上传了export部分的代码，可以参考README中的说明进行export。若有疑问，欢迎进一步交流。

**Comment by lmk123568** [comment]
> > 提供的pkl文件怎么加载到yolov5然后导出onnx？
> 
> 您好，感谢您的关注和提问！我们已经上传了export部分的代码，可以参考README中的说明进行export。若有疑问，欢迎进一步交流。

试了，导不出来
报错如下
```python
Downloading https://ultralytics.com/assets/Arial.ttf to /root/.config/Ultralytics/Arial.ttf...
export: data=/content/PAGCP/data/coco128.yaml, weights=/content/yolov5m_prune.pkl, imgsz=[640, 640], batch_size=1, device=cpu, half=False, inplace=False, train=False, optimize=False, int8=False, dynamic=True, simplify=False, opset=11, include=['onnx']
YOLOv5 🚀 v1.0-alpha-16-g4a81b86 torch 2.0.0+cu118 CPU

Fusing layers... 
Traceback (most recent call last):
  File "/content/PAGCP/export.py", line 319, in <module>
    main(opt)
  File "/content/PAGCP/export.py", line 314, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/PAGCP/export.py", line 260, in run
    y = model(im)  # dry runs
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/PAGCP/models/yolo.py", line 123, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/content/PAGCP/models/yolo.py", line 145, in _forward_once
    x = m(x)  # run
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/upsampling.py", line 157, in forward
    recompute_scale_factor=self.recompute_scale_factor)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'
```

**Comment by HankYe** [comment]
> 

这个应该是pytorch版本过高导致的，我们的实验是在torch 1.8.0的版本下进行的，您可以降到1.9的版本试试看

**Comment by lmk123568** [comment]
> > 
> 
> 这个应该是pytorch版本过高导致的，我们的实验是在torch 1.8.0的版本下进行的，您可以降到1.9的版本试试看

能不能发几个onnx模型，让大家不用再折腾，快速试一下效果

**Comment by HankYe** [comment]
> > > 
> > 
> > 
> > 这个应该是pytorch版本过高导致的，我们的实验是在torch 1.8.0的版本下进行的，您可以降到1.9的版本试试看
> 
> 能不能发几个onnx模型，让大家不用再折腾，快速试一下效果

你好，对应的onnx模型已经发布在release中。若有疑问，欢迎进一步交流。

**Comment by lmk123568** [comment]
> > > > 
> > > 
> > > 
> > > 这个应该是pytorch版本过高导致的，我们的实验是在torch 1.8.0的版本下进行的，您可以降到1.9的版本试试看
> > 
> > 
> > 能不能发几个onnx模型，让大家不用再折腾，快速试一下效果
> 
> 你好，对应的onnx模型已经发布在release中。若有疑问，欢迎进一步交流。

你发的yolov5m.onnx结构有问题
我换成yolov5官方提供的yolov5m.onnx，与prune的模型做了测试，onnx cpu下确实有一定的速度提升

**Comment by HankYe** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 这个应该是pytorch版本过高导致的，我们的实验是在torch 1.8.0的版本下进行的，您可以降到1.9的版本试试看
> > > 
> > > 
> > > 能不能发几个onnx模型，让大家不用再折腾，快速试一下效果
> > 
> > 
> > 你好，对应的onnx模型已经发布在release中。若有疑问，欢迎进一步交流。
> 
> 你发的yolov5m.onnx结构有问题 我换成yolov5官方提供的yolov5m.onnx，与prune的模型做了测试，onnx cpu下确实有一定的速度提升

好的，感谢您对我们工作的关注和探索。yolov5m.onnx的结构问题如果方便的话可以提供一下问题信息，以便我们进行测试调整，谢谢！

**Comment by lmk123568** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 这个应该是pytorch版本过高导致的，我们的实验是在torch 1.8.0的版本下进行的，您可以降到1.9的版本试试看
> > > > 
> > > > 
> > > > 能不能发几个onnx模型，让大家不用再折腾，快速试一下效果
> > > 
> > > 
> > > 你好，对应的onnx模型已经发布在release中。若有疑问，欢迎进一步交流。
> > 
> > 
> > 你发的yolov5m.onnx结构有问题 我换成yolov5官方提供的yolov5m.onnx，与prune的模型做了测试，onnx cpu下确实有一定的速度提升
> 
> 好的，感谢您对我们工作的关注和探索。yolov5m.onnx的结构问题如果方便的话可以提供一下问题信息，以便我们进行测试调整，谢谢！

`onnx.checker.check_model`用这个api看一下能不能加载，我这边在colab显示不能加载，你试一下吧

**Comment by HankYe** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 这个应该是pytorch版本过高导致的，我们的实验是在torch 1.8.0的版本下进行的，您可以降到1.9的版本试试看
> > > > > 
> > > > > 
> > > > > 能不能发几个onnx模型，让大家不用再折腾，快速试一下效果
> > > > 
> > > > 
> > > > 你好，对应的onnx模型已经发布在release中。若有疑问，欢迎进一步交流。
> > > 
> > > 
> > > 你发的yolov5m.onnx结构有问题 我换成yolov5官方提供的yolov5m.onnx，与prune的模型做了测试，onnx cpu下确实有一定的速度提升
> > 
> > 
> > 好的，感谢您对我们工作的关注和探索。yolov5m.onnx的结构问题如果方便的话可以提供一下问题信息，以便我们进行测试调整，谢谢！
> 
> `onnx.checker.check_model`用这个api看一下能不能加载，我这边在colab显示不能加载，你试一下吧

你好，我们测试了一下可以正常加载，实验用的onnx版本是1.12.0。
