### ISSUE TITLE
compress.py文件运行不成功

### ISSUE THREAD

**Issue by Macarena-lss** [HankYe/PAGCP#4]
作者您好！请问一下我在colab上运行这条命令!python compress.py --model yolov5s.yaml --dataset COCO --data coco.yaml --batch 64 --weights /content/PAGCP-main/yolov5s.pt --initial_rate 0.06 --initial_thres 6. --topk 0.8 --exp --device 0后，
pruning 0/51: group3, base_loss:539.222351, base_b:215.046875, base_o:243.176361, base_c:80.999107, ratio:0.05, thres:0.06
 10% 4/40 [00:02<00:22,  1.61it/s]一直卡在这里，请问是什么原因。

**Comment by HankYe** [comment]
> 作者您好！请问一下我在colab上运行这条命令!python compress.py --model yolov5s.yaml --dataset COCO --data coco.yaml --batch 64 --weights /content/PAGCP-main/yolov5s.pt --initial_rate 0.06 --initial_thres 6. --topk 0.8 --exp --device 0后， pruning 0/51: group3, base_loss:539.222351, base_b:215.046875, base_o:243.176361, base_c:80.999107, ratio:0.05, thres:0.06 10% 4/40 [00:02<00:22, 1.61it/s]一直卡在这里，请问是什么原因。

您好，请问您的yolov5s.pt的版本是多少？我们是在yolov5_5.0的版本上进行实验的，如果版本相同的话那么我们这里在终端上跑是能跑的，可能要检查是否是由colab引起的问题。如果版本不同的话可能是由于版本不同导致网络结构发生变化，这样的话group需要重新划分。
