### ISSUE TITLE
Error while replicating the flow suggested in Readme.md

### ISSUE THREAD

**Issue by max190** [HankYe/PAGCP#5]
I git cloned the repository and tried to run the flow suggested in the README.md and run the compress.py file, but I get an error as "Start Pruning" step begins.
Attaching the image to show the corresponding error.
Error: "RuntimeError: result type Float can't be cast to the desired output type long int"
Command: python compress.py --model test1 --dataset COCO --data coco.yaml --batch 64 --weights yolov5s.pt --initial_rate 0.06 --initial_thres 6. --topk 0.8 --exp --device 0

![image](https://user-images.githubusercontent.com/26062874/235621535-4540e6dd-6fe1-437d-9418-7cc6f28019a0.png)

**Comment by HankYe** [comment]
Hi, @max190. You can refer to [this issue](https://github.com/ultralytics/yolov5/issues/8405) for more help. To address this problem, you may either degrade the pytorch version or upgrade the yolov5 code.
